spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${LOCAL_PSQL_URL}
    username: ${LOCAL_PSQL_USERNAME}
    password: ${LOCAL_PSQL_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# google OAuth (소셜 로그인) 설정
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: ${GOOGLE_CLIENT_ID}
#            client-secret: ${GOOGLE_CLIENT_SECRET}
#            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
#            scope:
#              - email
#              - profile

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:86400000}   # 값 없으면 기본 1일
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000}  # 값 없으면 기본 7일

# S3 설정
cloud:
  aws:
    credentials:
      access-key: ${DEV_AWS_ACCESS_KEY_ID}
      secret-key: ${DEV_AWS_SECRET_ACCESS_KEY}
    s3:
      bucket: ${DEV_AWS_BUCKET}
    region: #S3 지역
      static: ap-northeast-2
    stack:
      auto: false

# logging:
#   level:
#     org.hibernate.SQL: debug
#     org.hibernate.type.descriptor.sql.BasicBinder: trace